### ISSUE TITLE
/n is ignored and doesn't create a new line, ending up showing in the final message

### ISSUE THREAD

**Issue by tikkou** [dragonfruitnetwork/dragon6#1]
![a2635c13-16cf-4b99-b85f-ee02eb839c12](https://user-images.githubusercontent.com/71342961/101533052-483c1080-398d-11eb-942c-1531cff5d835.jpg)

**Comment by aspriddell** [comment]
i'll take that up with xf.material at some point. For a workaround would just replacing them with a space do for now?

**Comment by tikkou** [comment]
yes

**Comment by aspriddell** [comment]
did some digging and found it was due to the dialog interpreting `\n` as a literal \n. Fixed with a hacky string replace (which works)

<img src="https://user-images.githubusercontent.com/10289119/101663826-0d94af80-3a43-11eb-9805-b4c0757146c7.png"  height="750"/>
