### ISSUE TITLE
A white aura appears during animations

### ISSUE THREAD

**Issue by tikkou** [dragonfruitnetwork/dragon6#2]
![20201208_195859](https://user-images.githubusercontent.com/71342961/101535425-871f9580-3990-11eb-9d94-f9d48d055c28.gif)

**Comment by tikkou** [comment]
there is also a white page at startup but I don't think it's a huge deal

**Comment by aspriddell** [comment]
The white page at startup is definitely something the app is doing. as for the white glow I think that's by default but i can always investigate ways to change it

**Comment by aspriddell** [comment]
this might be relevant and if it works, will be almost a single-line-change
https://forums.xamarin.com/discussion/125465/page-push-gt-flickering-blinking-on-dark-background

**Comment by aspriddell** [comment]
yeah... that fixed both issues you mentioned... I'll have that included in the next update

**Comment by aspriddell** [comment]
resolved in 2021.6-rc1 (see discord #andrdoid-test)
