### ISSUE TITLE
translation not applied (xp gained, op stats)

### ISSUE THREAD

**Issue by tikkou** [dragonfruitnetwork/dragon6#8]
![image](https://user-images.githubusercontent.com/71342961/108239744-1e982600-7142-11eb-9ccb-adc003a1c46e.png)

**Comment by aspriddell** [comment]
thanks for that - i'll get it updated on next pass (today/tomorrow)

**Comment by tikkou** [comment]
found this one too
![image](https://user-images.githubusercontent.com/71342961/108250639-658c1880-714e-11eb-96cf-92c58d0b95dc.png)

**Comment by aspriddell** [comment]
resolved all in dev branch - will push an update tomorrow (includes a load of updates and some performance boosts)

**Comment by aspriddell** [comment]
added in 2020.2-android-test
